# Generated by Django 4.1.5 on 2023-01-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_rename_dateadded_input_lastupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='lastUpdate',
            new_name='last_update',
        ),
    ]
